baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md

#custom
title: 我的炫酷博客
description: 这是我的个人博客，分享技术和生活。
url: https://richcorgi.github.io
theme: 主题名称（如果主题有指定）
